AllCops:
  TargetRubyVersion: 2.7
  Include:
  - "**/*.rb"
  - "**/*.rake"
  - "**/Gemfile"
  Exclude:
  - ".git/**/*"
  - "tmp/**/*"
  - "true/**/*"
  - "vendor/**/*"


Layout/EmptyLineAfterGuardClause:
  # Add empty line after guard clause.
  Enabled: false


Metrics/AbcSize:
  # A calculated magnitude based on number of assignments, branches, and conditions.
  Enabled: false

Metrics/BlockLength:
  # Avoid long blocks with many lines.
  Exclude:
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  # A complexity metric that is strongly correlated to the number of test cases needed to validate a method.
  Max: 10

Metrics/LineLength:
  # Limit lines to 100 characters.
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  # Avoid methods longer than 25 lines of code.
  Max: 25


Style/AsciiComments:
  # This cop checks for non-ascii (non-English) characters in comments.
  #
  # NLC: Disabling this so we can use non-breaking spaces (' ') in documentation comments, preventing browsers from collapsing
  #      multiple spaces in code blocks.
  Enabled: false

Style/BlockDelimiters:
  # Check for uses of braces or do/end around single line or multi-line blocks.
  Exclude:
    - 'spec/**/*.rb'

Style/ClassAndModuleChildren:
  # Use nested modules/class definitions instead of compact style.
  Enabled: false

Style/FrozenStringLiteralComment:
  # Add the frozen_string_literal comment to the top of files to help transition to frozen string literals by default.
  Enabled: false

Style/NumericLiterals:
  # his cop checks for big numeric literals without _ between groups of digits in them.
  Enabled: false

Style/RegexpLiteral:
  # Enforces using / or %r around regular expressions.
  EnforcedStyle: percent_r
